### ISSUE TITLE
InvalidTexture

### ISSUE THREAD

**Issue by Timong-craft** [lemonhandgrenade/hp-datapack#3]
**InvalidTexture**
Some of the texures like from wands don't show up they are only the minecraft invalid item

**To Reproduce**
Steps on how you got to the issue:
1. Type '/function hp:items/wand/spruce/spruce_phoenix_feather'
2. See error

**Expected behavior**
A description of what you expected to happen.

**What actually happened**
A description of what happened in game.

**Screenshots**
![image](https://user-images.githubusercontent.com/77288029/181089881-9681307a-cefa-4434-b52b-ca8ba29bf8aa.png)

**Version (please complete the following information):**
- Mods Sodium
 - Version 1.18.2

**Comment by lemonhandgrenade** [comment]
I'll tag this as known and keep it open till next release.
All wands hopefully eventually will all have unique models but because they're not done Minecraft can't find them.
I'll make all incomplete ones refer to a default in the mean time.

**Comment by Timong-craft** [comment]
Ok
