### ISSUE TITLE
Cloak Of Invisibility [Priority: Low]

### ISSUE THREAD

**Issue by Timong-craft** [lemonhandgrenade/hp-datapack#4]
**Describe the bug**
The "Cloak Of Invisibility" is very cool but there are two items that are almost the same only the description isn't the same

**To Reproduce**
1. Type '/function hp:items/clothes/chest/cloak_of_invisibility'
Screenshot: 
![image](https://user-images.githubusercontent.com/77288029/181190613-bb2c74d1-07c6-4554-b244-f5443f86e455.png)

2. Type '/function hp:items/clothes/chest/invisibility_cloak'
Screenshot: 
![image](https://user-images.githubusercontent.com/77288029/181190765-4b1abee2-f18e-4de1-b4f8-3bf5d2052b38.png)
5. See two items

**Expected behavior**
There are two Items that do the same thing

**Version (please complete the following information):**
- Mods Sodium, RoughlyEnoughItems
 - Version 1.18.2

**Comment by lemonhandgrenade** [comment]
This is more so mentioned in the books but is the cloak of invisibility which is on of the Deathly Hallows and then there are invisibility cloaks which are hexed cloaks

They're basically the same thing though the cloak of invisibility is more powerful.

**Comment by Timong-craft** [comment]
Oh, I`m from Germany and I didn't understood "Deathly Hallow" and Google Translate said something completly diferent but now I understand
