### ISSUE TITLE
Wand gets removed when you cast a spell

### ISSUE THREAD

**Issue by Randowithnolife** [lemonhandgrenade/hp-datapack#7]

**Comment by lemonhandgrenade** [comment]
Which version are you playing on?
As it sounds like the issue could be caused from pre world height change.

**Comment by Randowithnolife** [comment]
1.19.2

**Comment by lemonhandgrenade** [comment]
Can you reproduce the bug and if so could you write how you get to it?

**Comment by lemonhandgrenade** [comment]
I'm going to mark this as closed for now.
If the problem persists in the latest release feel free to reopen or open another issue
